name: Img-scan
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
  
        - name: Check out code
          uses: actions/checkout@v1

        - name: Run command
          run: |
           gcloud auth configure-docker us-central1-docker.pkg.dev
           docker pull \
               us-central1-docker.pkg.dev/vminstance-414214/frontend/python_img:latest

        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
           image-ref: us-central1-docker.pkg.dev/vminstance-414214/frontend/python_img:latest
           format: 'sarif'
           output: 'trivy-results.sarif'
          env:
           GOOGLE_APPLICATION_CREDENTIAL: ${{ secrets.GSA_KEY }}
      

        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v2
          with:
           sarif_file: 'trivy-results.sarif'