name: Build application

on:
    push:
        branches:
          - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v2
            
            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v2
              with:
                credentials_json: ${{ secrets.GSA_KEY }}
            - name: Set up gcloud CLI
              uses: google-github-actions/setup-gcloud@v2
              with:
                project_id: ${{ secrets.GOOGLE_PROJECT}}
            - name: build and push docker image
              env:
                GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT}}   
              run: |
               gcloud auth configure-docker us-central1-docker.pkg.dev           
               docker build -t us-central1-docker.pkg.dev/vminstance-414214/frontend/ .
               docker push us-central1-docker.pkg.dev/vminstance-414214/frontend/
